from __future__ import annotations

from pathlib import Path
from typing import Dict

import typer
from rich.console import Console
from rich.table import Table

from mandragora import __version__
from mandragora.prepare import run_prepare
from mandragora.intron import run_intron_analysis
from mandragora.omen import run_omen_analysis
from mandragora.repeat_overlap import run_repeat_overlap_analysis


app = typer.Typer(
    name="mandragora",
    help=(
        "Project MANDRAGORA: a bioinformatics toolkit for diagnosing "
        "intron architecture, repeat entanglement, and annotation weirdness "
        "in rare, parasitic, and repeat-rich plant genomes."
    ),
    add_completion=False,
)

console = Console()


def print_output_table(title: str, outputs: Dict[str, Path]) -> None:
    """
    Pretty-print output files generated by a MANDRAGORA command.
    """
    table = Table(title=title)
    table.add_column("Output", style="bold")
    table.add_column("Path")

    for name, path in outputs.items():
        table.add_row(name, str(path))

    console.print(table)


@app.command("version")
def version() -> None:
    """
    Show the installed MANDRAGORA version.
    """
    console.print(f"[bold green]Project MANDRAGORA[/bold green] v{__version__}")


@app.command("intron")
def intron(
    annotation: Path = typer.Option(
        ...,
        "--annotation",
        "-a",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Input genome annotation file in GFF3/GTF-like format.",
    ),
    outdir: Path = typer.Option(
        Path("results/intron"),
        "--outdir",
        "-o",
        file_okay=False,
        dir_okay=True,
        writable=True,
        help="Output directory for intron analysis results.",
    ),
) -> None:
    """
    Infer introns from exon coordinates and generate intron statistics.
    """
    console.print("[bold green]Running MANDRAGORA intron analysis...[/bold green]")
    console.print(f"Annotation: [cyan]{annotation}[/cyan]")
    console.print(f"Output directory: [cyan]{outdir}[/cyan]")

    outputs = run_intron_analysis(
        annotation_path=annotation,
        outdir=outdir,
    )

    console.print("[bold green]Intron analysis completed.[/bold green]")
    print_output_table("MANDRAGORA intron outputs", outputs)


@app.command("repeat-overlap")
def repeat_overlap(
    genes: Path = typer.Option(
        ...,
        "--genes",
        "-g",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Input gene annotation file in GFF3/GTF-like format or BED.",
    ),
    repeats: Path = typer.Option(
        ...,
        "--repeats",
        "-r",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Input repeat annotation file in BED format.",
    ),
    outdir: Path = typer.Option(
        Path("results/repeat_overlap"),
        "--outdir",
        "-o",
        file_okay=False,
        dir_okay=True,
        writable=True,
        help="Output directory for gene-repeat overlap results.",
    ),
) -> None:
    """
    Analyze overlap between gene coordinates and repeat annotations.
    """
    console.print("[bold green]Running MANDRAGORA gene-repeat overlap analysis...[/bold green]")
    console.print(f"Genes: [cyan]{genes}[/cyan]")
    console.print(f"Repeats: [cyan]{repeats}[/cyan]")
    console.print(f"Output directory: [cyan]{outdir}[/cyan]")

    outputs = run_repeat_overlap_analysis(
        gene_path=genes,
        repeat_bed_path=repeats,
        outdir=outdir,
    )

    console.print("[bold green]Gene-repeat overlap analysis completed.[/bold green]")
    print_output_table("MANDRAGORA repeat-overlap outputs", outputs)


@app.command("prepare")
def prepare(
    annotation: Path = typer.Option(
        None,
        "--annotation",
        "-a",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Optional genome annotation file in GFF3/GTF-like format.",
    ),
    repeats: Path = typer.Option(
        None,
        "--repeats",
        "-r",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Optional repeat annotation file in BED format.",
    ),
    genome: Path = typer.Option(
        None,
        "--genome",
        "-g",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Optional genome FASTA file.",
    ),
    outdir: Path = typer.Option(
        Path("results/prepare"),
        "--outdir",
        "-o",
        file_okay=False,
        dir_okay=True,
        writable=True,
        help="Output directory for preparation report.",
    ),
) -> None:
    """
    Inspect input files and generate a simple preparation report.
    """
    console.print("[bold green]Running MANDRAGORA prepare...[/bold green]")

    outputs = run_prepare(
        annotation_path=annotation,
        repeats_path=repeats,
        genome_path=genome,
        outdir=outdir,
    )

    console.print("[bold green]Prepare step completed.[/bold green]")
    print_output_table("MANDRAGORA prepare outputs", outputs)

@app.command("omen")
def omen(
    annotation: Path = typer.Option(
        ...,
        "--annotation",
        "-a",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Input genome annotation file in GFF3/GTF-like format.",
    ),
    repeats: Path = typer.Option(
        ...,
        "--repeats",
        "-r",
        exists=True,
        file_okay=True,
        dir_okay=False,
        readable=True,
        help="Input repeat annotation file in BED format.",
    ),
    outdir: Path = typer.Option(
        Path("results/omen"),
        "--outdir",
        "-o",
        file_okay=False,
        dir_okay=True,
        writable=True,
        help="Output directory for gene omen results.",
    ),
    long_gene: int = typer.Option(
        100_000,
        "--long-gene",
        help="Gene length threshold for long gene warning.",
    ),
    very_long_gene: int = typer.Option(
        500_000,
        "--very-long-gene",
        help="Gene length threshold for very long gene warning.",
    ),
    long_intron: int = typer.Option(
        100_000,
        "--long-intron",
        help="Maximum intron length threshold for long intron warning.",
    ),
    very_long_intron: int = typer.Option(
        500_000,
        "--very-long-intron",
        help="Maximum intron length threshold for very long intron warning.",
    ),
    repeat_warning: float = typer.Option(
        0.25,
        "--repeat-warning",
        help="Repeat fraction threshold for moderate repeat warning.",
    ),
    repeat_high: float = typer.Option(
        0.50,
        "--repeat-high",
        help="Repeat fraction threshold for high repeat warning.",
    ),
    repeat_severe: float = typer.Option(
        0.75,
        "--repeat-severe",
        help="Repeat fraction threshold for severe repeat warning.",
    ),
    short_gene: int = typer.Option(
        300,
        "--short-gene",
        help="Gene length threshold for short gene warning.",
    ),
) -> None:
    """
    Score genes for suspicious architecture and repeat-associated weirdness.
    """
    console.print("[bold green]Running MANDRAGORA omen analysis...[/bold green]")
    console.print(f"Annotation: [cyan]{annotation}[/cyan]")
    console.print(f"Repeats: [cyan]{repeats}[/cyan]")
    console.print(f"Output directory: [cyan]{outdir}[/cyan]")

    outputs = run_omen_analysis(
        annotation_path=annotation,
        repeat_bed_path=repeats,
        outdir=outdir,
        long_gene_threshold=long_gene,
        very_long_gene_threshold=very_long_gene,
        long_intron_threshold=long_intron,
        very_long_intron_threshold=very_long_intron,
        repeat_warning_fraction=repeat_warning,
        repeat_high_fraction=repeat_high,
        repeat_severe_fraction=repeat_severe,
        short_gene_threshold=short_gene,
    )

    console.print("[bold green]Omen analysis completed.[/bold green]")
    print_output_table("MANDRAGORA omen outputs", outputs)

if __name__ == "__main__":
    app()
